DROP TABLE IF EXISTS answer_notifications;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS themes;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles
(
    id   SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE users
(
    id         SERIAL PRIMARY KEY,
    role_id    BIGINT UNSIGNED NOT NULL,
    login      VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE themes
(
    id   SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE questions
(
    id        SERIAL PRIMARY KEY,
    user_id   BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    theme_id  BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (theme_id) REFERENCES themes (id) ON DELETE CASCADE ON UPDATE CASCADE,
    text      TEXT,
    completed BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE answers
(
    id          SERIAL PRIMARY KEY,
    user_id     BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    question_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE ON UPDATE CASCADE,
    text        TEXT NOT NULL
);

CREATE TABLE answer_notifications
(
    id        SERIAL PRIMARY KEY,
    answer_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (answer_id) REFERENCES answers (id) ON DELETE NO ACTION ON UPDATE CASCADE,
    is_read   BOOLEAN NOT NULL DEFAULT 0,
    user_id   BIGIINT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);
