<?php
// autogenerated!
// DO NOT EDIT MANUALLY
use Src\Route;
Route::get('pages/qqpp', [Controllers\PageController::class, 'index']);
Route::get('pages/lf', [Controllers\PageController::class, 'index']);