volumes:
  db-dev:
services:
  db:
    image: mariadb:10.7
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-db}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-QWEasd123!}
      MYSQL_USER: ${USER:-user}
      MYSQL_PASSWORD: ${PASSWORD:-password}
    volumes:
      - db-dev:/var/lib/mysql
